all:
  children:
    master:
      hosts:
        fatman.klmn.sh:
    workers:
      hosts:
        ny-res.greatinet.org:
        salmon.greatinet.org:
        nl.vpnclub.org:
          ansible_user: cloud-user
          tailscale_exit_node: true
          open_ports:
            - port: "45383"
              proto: both
              comment: "Shadowbox access keys"
            - port: "33287"
              proto: tcp
              comment: "Shadowbox management API"
        dolma.greatinet.org:
    enter:
      hosts:
        enter.greatinet.org:
          out_of_tailnet: true
          enabled: true
          manager_user: true
          open_ports:
            - port: "51820"
              proto: udp
              comment: "WireGuard"
  vars:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
    ansible_become: true
    ansible_become_method: sudo
