all:
  children:
    master:
      hosts:
        fatman.klmn.sh:
        dc.vpnclub.org:
          tailscale_exit_node: true
          open_ports:
            - port: "6362"
              proto: both
              comment: "Shadowbox access keys"
            - port: "19243"
              proto: tcp
              comment: "Shadowbox management API"
        nl.vpnclub.org:
          tailscale_exit_node: true
          open_ports:
            - port: "45383"
              proto: both
              comment: "Shadowbox access keys"
            - port: "33287"
              proto: tcp
              comment: "Shadowbox management API"
    workers:
      hosts:
        mrdr.greatinet.org:
          out_of_tailnet: true
  vars:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
    ansible_become: true
    ansible_become_method: sudo
